03 homework
TarIryna/nodejs-homework-rest-api pull request #4
Opened 2021-11-30 20:55 UTC by TarIryna

сделала дз 3

2021-11-30 21:28 UTC, KirillKulakow commented on .env
> +PORT = 3001
файл удалить из гита и добавить в gitignore

2021-11-30 21:30 UTC, KirillKulakow commented on .env
> +const MONGO_URL =
так не пишут в .env файлах
большими буквами переменная потом = и строка без кавычек
`MONGO_URL = mongodb+srv://tar86irina:t02031986@cluster0.s2urx.mongodb.net/Contacts?retryWrites=true&w=majority`

2021-11-30 21:30 UTC, KirillKulakow commented on db/connection.js
> +const MONGO_URL =
переписать на использование переменной среды

2021-11-30 21:30 UTC, KirillKulakow commented on model/contacts.json
> -[{"id":1,"name":"Allen Raymond","email":"nulla.ante@vestibul.co.uk","phone":"(992) 914-3792"},{"id":2,"name":"Chaim Lewis","email":"dui.in@egetlacus.ca","phone":"(294) 840-6685"},{"id":3,"name":"Kenn
этот файл тебе нужен?

2021-11-30 21:31 UTC, KirillKulakow commented on package.json
> +    "mongodb": "^4.2.0",
зачем данный пакет?

2021-11-30 21:32 UTC, KirillKulakow commented on routes/api/contactsRouter.js
> +router.patch("/:contactId/favorite", asyncWrapper(updateFavoriteController));
добавить валидацию входящего параметра

2021-11-30 21:33 UTC, KirillKulakow commented on routes/controllers/contactsController.js
> +  const result = await Contact.findById(id);
было бы лучше возвращать ошибку если контакт не найден со статусом 404

2021-11-30 21:35 UTC, KirillKulakow commented on routes/controllers/contactsController.js
> +  const id = req.params.contactId;
сделать проверку на корректный входящий ид

2021-11-30 21:35 UTC, KirillKulakow commented on routes/controllers/contactsController.js
> +  const id = req.params.contactId;
сделать проверку на корректный ид

2021-11-30 21:35 UTC, KirillKulakow commented on routes/controllers/contactsController.js
> +  const id = req.params.contactId;
сделать проверку на корректный ид

2021-11-30 21:36 UTC, KirillKulakow commented on routes/controllers/contactsController.js
> +  const id = req.params.contactId;
так же

2021-11-30 21:36 UTC, KirillKulakow requested changes
Need fix

2021-12-02 11:16 UTC, TarIryna commented on package.json
> +    "bcrypt": "^5.0.1",
начала делать дз, поэтому установила

2021-12-02 21:28 UTC, KirillKulakow approved these changes

2021-12-03 18:41 UTC, merged